# Generated by Django 5.2.7 on 2025-11-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='token_ws',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('IN_PROGRESS', 'En preparación'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('PAID', 'Pagado'), ('FAILED', 'Fallido')], default='NEW', max_length=20),
        ),
    ]
